server:
  port: ${EUREKA_SERVER_PORT:8761}

spring:
  zipkin:
    base-url: ${ZIPKIN_SERVER_URL:http://localhost:9411}
  boot:
    admin:
      client:
        url: ${ADMIN_SERVER_URL:http://localhost:8886}

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  server:
    eviction-interval-timer-in-ms: 1000
  instance:
    hostname: ${EUREKA_SERVER_HOST:localhost}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

logging:
  level:
    ROOT: INFO
    com.netflix.eureka: 'OFF'
  file:
    max-history: 0
    max-size: 1GB
default:
  locale: en_US