server:
  port: ${CORE_PORT:1905}

spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: ${CORE_H2_USERNAME:h2}
    password: ${CORE_H2_PASSWORD:123}
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  boot:
    admin:
      client:
        url: ${ADMIN_SERVER_URL:http://localhost:8886}
  zipkin:
    base-url: ${ZIPKIN_SERVER_URL:http://localhost:9411}

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  instance:
    preferIpAddress: false
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

logging:
  level:
    ROOT: INFO
    feign:
      Logger: DEBUG
  file:
    max-history: 0
    max-size: 1GB
default:
  locale: en_US

swagger:
  api-info:
    title: Finartz Flight Agency Core
    description: In this web page, you can interact with API resources of Flight Agency Demo Application
    version: 1.0.0-SNAPSHOT
    terms-of-service-url: 'https://generator.lorem-ipsum.info/terms-and-conditions'
    contact:
      name: Oguz Erhan Eker
      url: 'https://www.linkedin.com/in/oguzerhaneker/'
      email: 'eker.oguz@gmail.com'
    license: 'Apache License Version 2.0'
    license-url: 'https://www.apache.org/licenses/LICENSE-2.0'
    vendor-extensions:
      -
        name: Finartz
        value: Flight Agency Demo Application

flight-agency:
  capacity-percentile-increment: 10.0
  price-percentage: 10.0
  scale: 2
